### ISSUE TITLE
pandas版本的reset_index不支持name了

### ISSUE THREAD

**Issue by chenbofeng123** [ShichenXie/scorecardpy#102]
TypeError: reset_index() got an unexpected keyword argument 'name'
1.+pandas版本不支持在这个函数里指定 name了！

**Comment by chenbofeng123** [comment]
可否提供一个更高的支持版本

**Comment by ShichenXie** [comment]
安装github上面的版本试试

**Comment by a-bear-child** [comment]
最新版本的woebin还有这个问题，我把.reset_index(name='a_sum')改成.rename('a_sum').reset_index()了，但后面又报了新的错

**Comment by ShichenXie** [comment]
你的pandas什么版本的

**Comment by ShichenXie** [comment]
这个问题应该解决了的
