### ISSUE TITLE
perf_eva() 函数报错问题

### ISSUE THREAD

**Issue by suiyilalala** [ShichenXie/scorecardpy#104]
谢老师好 perf_eva() 使用过程中报错如下：
ValueError: Number of rows must be a positive integer, not 1.0
`ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_4740\3289853055.py in <module>
      1 # performance ks & roc ------
----> 2 train_perf = sc.perf_eva(y_train, train_pred, title = "train")
      3 test_perf = sc.perf_eva(y_test, test_pred, title = "test")

E:\Anaconda\lib\site-packages\scorecardpy\perf.py in perf_eva(label, pred, title, groupnum, plot_type, show_plot, positive, seed)
    316         fig = plt.figure()
    317         for i in np.arange(len(plist)):
--> 318             plt.subplot(subplot_nrows,subplot_ncols,i+1)
    319             eval(plist[i])
    320         plt.show()`

**Comment by suiyilalala** [comment]
我用的是example里的代码 。numpy版本是1.21.5， 会不会是依赖包的版本问题啊

**Comment by suiyilalala** [comment]
> 
我用的是example里的代码 。numpy版本是1.21.5， 会不会是依赖包的版本问题啊

**Comment by suiyilalala** [comment]
![image](https://github.com/ShichenXie/scorecardpy/assets/50371172/edacd96c-3d29-4e5f-ae7a-bd17b614a83a)
ceil函数向上取整返回的是浮点数，但是subplot()函数需要传的参数是整数，这应该就是报错 ‘ValueError: Number of rows must be a positive integer, not 1.0’ 的原因了

**Comment by ShichenXie** [comment]
新版本matplotlib不支持了。已经修复，谢谢
