### ISSUE TITLE
运行你的example中train_perf = sc.perf_eva(y_train, train_pred, title = "train")

### ISSUE THREAD

**Issue by ggfggggjqd** [ShichenXie/scorecardpy#105]
出现以下报错ValueError: Number of rows must be a positive integer, not 1.0

<Figure size 432x288 with 0 Axes>

**Comment by suiyilalala** [comment]
已经有相关提问了， 作者已经修复， 下载github上的最新版本依赖包就可以了。

**Comment by ggfggggjqd** [comment]
> 
已经是最新的
0.1.9.6 了

**Comment by suiyilalala** [comment]
最新是1.9.7

**Comment by rookiebird** [comment]
matplotlib降级到3.4.1也可以

**Comment by ShichenXie** [comment]
已经将这个问题的修复版本上传PYPI了。
