### ISSUE TITLE
woe分箱问题

### ISSUE THREAD

**Issue by mitudelu** [ShichenXie/scorecardpy#107]
<img width="502" alt="截屏2023-06-19 10 55 19" src="https://github.com/ShichenXie/scorecardpy/assets/59481548/623c042d-06a4-4acb-b5e3-104fd7f81a56">
您好，有个疑问需要您帮忙解答一下爱，请问woe分箱这一块儿  为什么不用训练集去分箱呀？而是使用全部数据

**Comment by ShichenXie** [comment]
这个数据集比较小。如果数据量相对合理，最好是基于训练集分箱。
