### ISSUE TITLE
woebin分箱结果异常

### ISSUE THREAD

**Issue by a-bear-child** [ShichenXie/scorecardpy#113]
想请问一下为什么woebin分组出来的的数据与deploy之后的数据有较大差异？并且特殊值好像没有成功分组，导致最终count的数量大于原数据
![1710926335710](https://github.com/ShichenXie/scorecardpy/assets/20807598/43fed3f0-48d4-4a05-8ac5-ebc6fc5bd613)
![1710926403347](https://github.com/ShichenXie/scorecardpy/assets/20807598/8822f875-0a35-4c1d-af21-fcd63c68239e)

**Comment by a-bear-child** [comment]
找到原因了，merge的时候把index重置了，下面not in的时候就会出错，自己手动改了一下，供参考
![1710936356605](https://github.com/ShichenXie/scorecardpy/assets/20807598/b9507ee9-0a9e-4e77-aac4-43fc15dc2b6e)

**Comment by a-bear-child** [comment]
deploy时特殊值赋值好像也有点问题，供参考
![image](https://github.com/ShichenXie/scorecardpy/assets/20807598/cdee0f7f-6e0c-4751-ac6c-83a3301746e7)

**Comment by ShichenXie** [comment]
有可重复的案例么

**Comment by a-bear-child** [comment]
不好意思刚才下了最新的包发现问题都修复过了 
实在不好意思
