### ISSUE TITLE
When the different values of a feature are greater than 50, the feature is removed.Here, I have a question.

### ISSUE THREAD

**Issue by sunrisehang** [ShichenXie/scorecardpy#13]
谢老师，打扰您一下！~

在您的源码里，rmcol_datetime_unique1(dat, check_char_num = False)函数中，如果这个变量的值，非数字且不同值大于50个，那么如果选择不分箱，也就是2，将会中止程序。

在几个星期之前，我使用pd.read_sql()函数时，就会将所有的数字全部都读取为object的格式。
起初我没注意到，代码运行到了这里，必须选1，我本想着选2，想着对这写数字列不分箱也可以。但这里格式不对，选2直接就停止运行了。

我想是不是再加个判断条件比较好呢？如果转换不成数字的格式，再进行中止程序。如果转换成数字的格式，可以提醒对方，该列已转换成数字格式，是否仍进行分箱？

这是我的想法哈~谢老师怎么认为的呢？

**Comment by ShichenXie** [comment]
r版本的已经有一个参数了，但是我没时间更新到python版本里。你可以对照看看

**Comment by ShichenXie** [comment]
如果你愿意，我可以把你加到python版本的作者里。不过要求就是先看懂r版本的，然后翻译成python版

**Comment by sunrisehang** [comment]
我愿意的啦~~~我会先看R语言的，在对python版的提意见。
括弧：其实我还有很多想法呢，正好核对一下R语言的，然后再给谢老师提python语言的建议，要不这样一直麻烦谢老师也不好哈哈。

**Comment by ShichenXie** [comment]
R版本比较依赖data.table包，你可以看看这个包的参考资料

**Comment by sunrisehang** [comment]
我会抓紧时间搞起来，早日让我们的python版本完美起来，我认为可以的哈哈哈~爱生活，爱python~哈哈哈

**Comment by ShichenXie** [comment]
这个问题应该已经解决了。不过不建议修改数据类型
