### ISSUE TITLE
var_filter.py#87

### ISSUE THREAD

**Issue by BenjaLeh** [ShichenXie/scorecardpy#15]
I guess the variable 'len_diff' in the warning function should be 'len_diff_var_kp', after several unsuccessed trys to pass a set of to-keep variables which contains more ones than the origin dataframe really has.

**Comment by sunrisehang** [comment]
I also discovered the problem, I have submitted it at 'Pull requests'.

**Comment by ShichenXie** [comment]
The bug has been fixed by @sunrisehang. Thanks.
