### ISSUE TITLE
What kind of tree does it use?

### ISSUE THREAD

**Issue by fsanzestevez** [ShichenXie/scorecardpy#26]
Hello, 

I am exploring the library in order to create a complex scorecard for my clients. I have always used 'smbinning' package in R because I really trust CIT when creating the tree, and I was wondering what kind of trees does scorecardpy use for the discretization process.

Thanks in advance

**Comment by ShichenXie** [comment]
Hi, the tree method using iv gain ratio and leaf number as stopping criterion. If you are familiar with R, try to use the R version package ‘scorecard’, which is much stable and faster. It will save your a lot of time to create a scorecard model.
