### ISSUE TITLE
Scorecard

### ISSUE THREAD

**Issue by Toon6115** [ShichenXie/scorecardpy#27]
Hi @ShichenXie,

If we calculate the woe by using ln(B/G) and we expect more score to have more default, I am not sure you are correct to calculate the score by -b*x['woe']*coef_df[i] + basepoints/len_x.

I think we should "b*x['woe']*coef_df[i] + basepoints/len_x", please correct me if I am wrong.

# scorecard
    len_x = len(coef_df)
    basepoints = a - b*model.intercept_[0]
    card = {}
    if basepoints_eq0:
        card['basepoints'] = pd.DataFrame({'variable':"basepoints", 'bin':np.nan, 'points':0}, index=np.arange(1))
        for i in coef_df.index:
            card[i] = bins.loc[bins['variable']==i,['variable', 'bin', 'woe']]\
              .assign(points = lambda x: round(-b*x['woe']*coef_df[i] + basepoints/len_x))\
              [["variable", "bin", "points"]]
    else:
        card['basepoints'] = pd.DataFrame({'variable':"basepoints", 'bin':np.nan, 'points':round(basepoints)}, index=np.arange(1))
        for i in coef_df.index:
            card[i] = bins.loc[bins['variable']==i,['variable', 'bin', 'woe']]\
              .assign(points = lambda x: round(-b*x['woe']*coef_df[i]))\
              [["variable", "bin", "points"]]
    return card

**Comment by ShichenXie** [comment]
The coefficients are not related with the definition of woe.
