### ISSUE TITLE
about the woebin

### ISSUE THREAD

**Issue by zeng8280** [ShichenXie/scorecardpy#29]
你好，打扰下，源码太长了 没仔细看，想调用best-ks分箱是哪个函数呀，另外有api文档吗， 因为有些代码好像没介绍完整

谢谢

**Comment by ShichenXie** [comment]
这个包是直接将R版本转写过来的，如果你能用R的话，推荐你先试试R版本的包。R版本的文档也比较完善，http://shichen.name/scorecard/.

如果对R不了解的话，可以直接跑python包每个函数的例子，应该把大部分的使用情景都包含进去了。

**Comment by NinaZMX** [comment]
您好，想问一下版本0.1.9.2和版本0.1.9.6的区别是什么呀？或者能在哪里看到吗？

**Comment by ShichenXie** [comment]
用最新的就可以了，python版本的包没有新功能上线，只是修复了bug。
