### ISSUE TITLE
var_filter.py

### ISSUE THREAD

**Issue by drlqvu** [ShichenXie/scorecardpy#30]
这个文件第87行的“len_diff”变量是未定义的。在特殊情况下会报错。
`  warnings.warn("Incorrect inputs; there are {} var_kp variables are not exist in input data, which are removed from var_kp. \n {}".format(len_diff, list(set(var_kp)-set(var_kp2))) )
`

**Comment by ShichenXie** [comment]
试试安装github上面的版本。这个bug应该早就修复了。
