### ISSUE TITLE
please, add parametr

### ISSUE THREAD

**Issue by sorochinsky** [ShichenXie/scorecardpy#31]
I want use woebin_ply on one row, but there's a check on unique:
"columns have only one unique values, which are removed from input dataset"
Please, add parametr in woebin_ply function to deactivate removing.

Thanks for your work!

**Comment by ShichenXie** [comment]
please try the latest version on the GitHub. This bug should be fixed. Please give me feed back. If there is no problem I'll upload it to the PyPi. Thanks.

**Comment by sorochinsky** [comment]
Everything works great. Thank you very much.
