### ISSUE TITLE
TypeError: unhashable type: 'list‘’

### ISSUE THREAD

**Issue by yangyangtongxue** [ShichenXie/scorecardpy#36]
![image](https://user-images.githubusercontent.com/39020254/68014243-ed37e480-fcc9-11e9-9054-0a5810e1ae8a.png)
![image](https://user-images.githubusercontent.com/39020254/68014434-8a931880-fcca-11e9-816a-15e62295319a.png)

我运行作者给的例子到“ train_woe = sc.woebin_ply(train, bins_adj)”这一步时报错

**Comment by ShichenXie** [comment]
如果python版本是3.7的，可能不适配，可以先用pyhon3.6的。

如果是python3.6版本的，可以先更新一下包。

**Comment by yangyangtongxue** [comment]
好吧，我用的是python3.7的，很荣幸得到谢老师的解答

**Comment by ShichenXie** [comment]
问题应该解决了
