### ISSUE TITLE
sc.woebin() 输出 bins 多了 index 的分箱

### ISSUE THREAD

**Issue by DongdongGui** [ShichenXie/scorecardpy#37]
scorecardpy 版本：v0.1.9.1
python : 3.7
问题描述：
采取woebin()函数分箱，如果输入DataFrame的index不是按顺序排列（没有reset_index()）
分箱结果将会产生index的分箱结果
代码：
dat = sc.germancredit()
dt_s = sc.var_filter(dat, y="creditability")
dt_s['index_x'] = [1*i for i in range(len(dt_s)-100)] + [2*i for i in range(100)]
dt_s = dt_s.set_index('index_x')
bins = sc.woebin(dt_s[['creditability','housing']], y="creditability")

**Comment by DongdongGui** [comment]
dat = sc.germancredit()
dt_s = sc.var_filter(dat, y="creditability")
dt_s['index_x'] = [1*i for i in range(len(dt_s)-100)] + [2*i for i in range(100)]
dt_s = dt_s.set_index('index_x')
bins = sc.woebin(dt_s[['creditability','housing']], y="creditability")

**Comment by DongdongGui** [comment]
添加代码，生成新的index，list遍历显示少了一个乘号，注意一下

**Comment by DongdongGui** [comment]
dat = sc.germancredit()
dt_s = sc.var_filter(dat, y="creditability")
dt_s['index_x'] = [1*i for i in range(len(dt_s)-100)] + [2*i for i in range(100)]
dt_s = dt_s.set_index('index_x')
bins = sc.woebin(dt_s[['creditability','housing']], y="creditability")

**Comment by DongdongGui** [comment]
“”“
dat = sc.germancredit()
dt_s = sc.var_filter(dat, y="creditability")
dt_s['index_x'] = [1i for i in range(len(dt_s)-100)] + [2i for i in range(100)]
dt_s = dt_s.set_index('index_x')
bins = sc.woebin(dt_s[['creditability','housing']], y="creditability")
”“”

**Comment by ShichenXie** [comment]
修复了https://github.com/ShichenXie/scorecardpy/commit/10e511fc909e53fbb8866e1dadfe23183f03ca0b
数据集里不能出现重复的index，出现的话就会reset
