### ISSUE TITLE
小数点问题

### ISSUE THREAD

**Issue by rockkb** [ShichenXie/scorecardpy#4]
当variable为0-1的值时，分箱后会出现小数点很长的情况，如下0.30000000000000004这样
variable | bin | points
credit_rate | [-inf,0.1) | -7.0
credit_rate | [0.30000000000000004,0.8) | 9.0
credit_rate | [0.30000000000000004,0.8) | 92.0
credit_rate | [0.8,inf) | -40.0

thank you。

**Comment by ShichenXie** [comment]
https://github.com/ShichenXie/scorecardpy/issues/3#issuecomment-432665216
你上一个问题，我回答清楚了么

**Comment by rockkb** [comment]
上一个问题，可以了。非常感谢
