### ISSUE TITLE
problem about woeply with special value

### ISSUE THREAD

**Issue by zhihuaZZH** [ShichenXie/scorecardpy#43]
这个python包给了我很大的帮助，非常感谢！但我也发现了一些问题，在使用等频分组（我是先找出等频cut再通过breaks_list参数传入）并woe替换的时候，发现了以下两个问题：
1、对于存在特殊值的分组，woe替换后并没有被替换成对应的woe值，还是对应区间的woe值...稍微看了一下源码，问题好像出在woepoints_ply1()这个函数中，最后在替换的时候，是先用woebin的breaks来对每个值cut，然后再和woebin中的bin进行merge，在merge之前，缺失值nan替换成了missing，但是其他特殊值并没有替换成对应的bin，最终导致merge的时候被分到了实际区间对应的组，而不是单独的那一组；
2、数值型特征等频分组后会出现最后一个break不是inf的情况，即使我已经强制替换成了inf，这样导致woeply的时候，属于最后一组的值替换后的woe值变成了NaN，因为右半区间不一样，merge的时候没有关联上；

**Comment by ShichenXie** [comment]
不建议你使用等频做初始分箱，会出现很多问题，我当初都踩过这些坑。当然你说等频没有inf是因为你没处理好。

**Comment by ShichenXie** [comment]
如果还碰到问题，提供一个可重现的数据和代码给我看看

**Comment by PollyAnnna** [comment]
请问为什么不建议用等频或等距做初始分箱呢？

**Comment by ShichenXie** [comment]
等频应该对应等高；等距对应的是等宽。
等频初始分箱容易出现比较奇怪的切割点，而且有可能两边的切割点是一致的，都需要特殊处理。
等宽初始分箱只要箱数多一些，就已经分的很细了，足够后面进行合并了。
