### ISSUE TITLE
大兄弟，你的WOE怎么reverse了

### ISSUE THREAD

**Issue by hdaijay** [ShichenXie/scorecardpy#44]
大兄弟，WOE = ln(good distribution/ bad distribution), in your case, bad or event is 1, but it become  bad distribution/ good distribution. 

Please correct me if I use the function in the wrong way. 

But, 这个package是目前最方便算WOE和手动调的，good job, 大兄弟

**Comment by hdaijay** [comment]
大兄弟啊，我直接用的是pip 的版本，也不知道你最新的版本是啥样，我感觉你的code 写了是bad|1. 但是我在调参数的时候bad|0 才是对的WOE。 

Big brother, I just used the pip version which I am not sure if the newest version. In your code, I saw you use the bad|1, however, I only use bad|0 to get the right results. thanks!

**Comment by ShichenXie** [comment]
如果希望woe是好/坏，可以设置positive=‘good/0’。我建模的时候是默认woe为坏/好的。

**Comment by hdaijay** [comment]
哦哦对哦，是这样的。默认bad/good也有道理，因为sklearn的LR只能target 1 或者event， 不能像SAS一样target 0， 所以coefficient都要改一下再乘上 WOE。
