### ISSUE TITLE
woebin_ply: AttributeError: 'DataFrame' object has no attribute 'explode'

### ISSUE THREAD

**Issue by yesareyouteahi** [ShichenXie/scorecardpy#45]
Hi,
I'm trying to build a scorecard and while transforming the input data to WOE values, I came across the above mentioned error. When I checked the source code, the input for woebin_ply is a dataframe. Could you please help me out on this?

**Comment by Okroshiashvili** [comment]
Do you have Pandas version 0.25.0 or higher? ```df.explode``` was introduced in that Pandas version.

**Comment by yesareyouteahi** [comment]
@Okroshiashvili   No. I had version 0.23.0 and upgraded it to 0.25.0. I figured it out after raising the issue😅. Thanks for the response.
