### ISSUE TITLE
selecting the best 20 variables

### ISSUE THREAD

**Issue by mariuszolszewski676** [ShichenXie/scorecardpy#49]
is there possible to implement top 20 vaiariables only into scorecard?

how to do it in the best statistitical way?

**Comment by karakastarik** [comment]
Of course Information Value (IV) can be used for this or you can look for the coefficients of the variables. [This](https://sundarstyles89.medium.com/weight-of-evidence-and-information-value-using-python-6f05072e83eb) article has a good explanation for IV and WoE.

**Comment by ShichenXie** [comment]
This is a big question, please try to search keywords like 'feature selection', or try to read ml textbook. For example, I searched 'ml feature selection' and got this [article](https://machinelearningmastery.com/feature-selection-with-real-and-categorical-data/).
