### ISSUE TITLE
'chimerge'  method problems in woebin.py

### ISSUE THREAD

**Issue by monicamn** [ShichenXie/scorecardpy#5]
Hi Dr Xie,

Thank you response to me first. I use woebin.py in 'chimerge' method.  There is no error to produce bins result.  But when bins result is applied to dataset, there is no 'inf' in the last break point so that 'nan' value compared in dataset after woebin.py. That means breaks cut can't cover all value. 

The result are as follows:

https://github.com/monicamn/test

 I am very appreciated for your reply.

**Comment by monicamn** [comment]
There is still something wrong with bins. Because "max_num_bin=8" is limited, the last bin break is not 'inf' when the number of bins is greater than 8. When the  number of bins is less than or equal to 8, the last bin break is 'inf'. The result is listed in 'woe_3.png' in  https://github.com/monicamn/test.

**Comment by monicamn** [comment]
I have some little suggestion about "woebin_plot". I want to save the images in my file. But The result is showed in the python console. These images are import for me to save and analysis.

**Comment by ShichenXie** [comment]
能把这列数据和Y发到我邮箱么，我这边复现不了你的问题。
