### ISSUE TITLE
Is it possible to set the scores manually after creating binning for features?

### ISSUE THREAD

**Issue by rubavathy** [ShichenXie/scorecardpy#50]

**Comment by rubavathy** [comment]
I would like to the scores manually for some of the features as it influences the Credit Scoring very largely. Pls let me know how it's possible?

**Comment by ShichenXie** [comment]
I don't think it is a good idea to manually set the score for some features. If the feature affects the total score very largely, you can try to use it in a rule directly, but not use it in a model.
