### ISSUE TITLE
AUC calculation

### ISSUE THREAD

**Issue by loveis98** [ShichenXie/scorecardpy#53]
Hello
Why you treats scores like this (in `perf_eva()` function)?
```
if np.mean(pred) < 0 or np.mean(pred) > 1:
        warnings.warn('Since the average of pred is not in [0,1], it is treated as predicted score but not probability.')
        pred = -pred
```
I mean string `pred = -pred` exactly

In case of positive scores your computing works incorrectly

**Comment by ShichenXie** [comment]
You can try to use the score as pred parameter to calculate the AUC value. It will return the right value.
