### ISSUE TITLE
Manually adjust the cut-off

### ISSUE THREAD

**Issue by billy-odera** [ShichenXie/scorecardpy#56]
I am trying to manually adjust the cut off for my variable age as below
```
break_adj = age[0.99, 1.99, 2]
bins_adj = sc.woebin(df, y="TARGET", breaks_list=break_adj, print_info=FALSE)
```
but i get the below error
`NameError: name 'age' is not defined`

**Comment by ShichenXie** [comment]
import scorecardpy as sc

df = sc.germancredit()

break_adj = {'age.in.years': [30, 40, 50]}
bins_adj = sc.woebin(df, y="creditability", x = ['age.in.years'], breaks_list=break_adj, print_info= False)

**Comment by ShichenXie** [comment]
Please read the help documentation of the package via help(sc.woebin) for example.
