### ISSUE TITLE
Huge variance in IV from 

### ISSUE THREAD

**Issue by billy-odera** [ShichenXie/scorecardpy#57]
I have noticed a very huge difference in IV when doing this 

```
dt_info_value = sc.iv(df, y = "FLAG")
dt_info_value
Variable                                | Info Value
HIGHEST_WITH_VALUE_6M | 0.299023
```

but when I do the binning 
```
bins_var = sc.woebin(df,y="FLAG", x="HIGHEST_WITH_VALUE_6M")
sc.woebin_plot(bins_var)
```

![image](https://user-images.githubusercontent.com/12785557/88839235-75a8ce80-d1e3-11ea-8977-1322bf37c507.png)

**what could be the reason and two how do i rotate the x axis values to be readable**

**Comment by ShichenXie** [comment]
The information value (iv) calculated in woebin function is also using the iv function. The difference between these two value is due to the iv function calculates information value without binning, but woebin function calculates it after binning.
