### ISSUE TITLE
gains table missing

### ISSUE THREAD

**Issue by billy-odera** [ShichenXie/scorecardpy#58]
I cant find the gains table function using
sc.gains_table

**Comment by ShichenXie** [comment]
yes, it's not provided in python version package. you can try to use r version, if you need to use this function .

**Comment by billy-odera** [comment]
Thanks, also can you advice on the 2 questions for clarification,I had raised

**Comment by billy-odera** [comment]
Also, how can i get the below reports similar to how i got the psi

- Pass rate analysis
- Vintage analysis
- Bad distribution
- Mobility analysis

**Comment by ShichenXie** [comment]
Currently, only r version package provides report function to export the topic you list above.
