### ISSUE TITLE
Dummy variables (0,1)

### ISSUE THREAD

**Issue by Anaxximandar** [ShichenXie/scorecardpy#6]
I have a data frame with dummy variables (among others).
However when I run:
bins = sc.woebin(mydf, y="MY_GOODBAD") the following error is received:
AttributeError: module '__main__' has no attribute '__spec__'

When I run the same command without dummy variables it is ok.
In R it was solved by 'factoring' dummy variables.
How to solve it in Python (Python 3.6)?

**Comment by ShichenXie** [comment]
If you are familiar with R, please use the R package, which is much stable. I will update the python package in the next few months. It will take some time, since I cant do it in full time.

**Comment by ShichenXie** [comment]
And please give me a sample data and the code to reproduce your issue.

**Comment by Anaxximandar** [comment]
[Data.xlsx](https://github.com/ShichenXie/scorecardpy/files/2869500/Data.xlsx)
[Data_no_dummies.xlsx](https://github.com/ShichenXie/scorecardpy/files/2869501/Data_no_dummies.xlsx)
[ScorecardTest.txt](https://github.com/ShichenXie/scorecardpy/files/2869502/ScorecardTest.txt)

**Comment by ShichenXie** [comment]
No error in my local environment. Try to install the python package from github, which is not upload to pypi yet.

**Comment by Anaxximandar** [comment]
I did it as you said and it works! 
I am looking forward to new features when available
