### ISSUE TITLE
Can we get for multilabel data?

### ISSUE THREAD

**Issue by hanzigs** [ShichenXie/scorecardpy#60]
Is it possible to occupy multilabel data?
Thanks

**Comment by ShichenXie** [comment]
Not in this package

**Comment by hanzigs** [comment]
Thanks,
May I know, Will this approach is efficient
#For Multi Label Classification
Just for WOE transforming data, we merge two classes to ONE in 3 classes data and make as binary and transform, then replace target with 3 classes before modelling
#For Regression
Here, take a binary feature with High Importance based on model and use that as a binary Target for WOE transformation, then replace the target with actual regression target before modelling.
Thanks for the advice.
