### ISSUE TITLE
perf_eva caculate

### ISSUE THREAD

**Issue by binxixi** [ShichenXie/scorecardpy#63]
the perf_eva function described:   pred: **Predicted probability** or **score**.
But when I use **Predicted probability** or **score** ,the result doesn't equal .

 **use Predicted probability**: KS =0.5286
```
train_pred = lr.predict_proba(x_train)[:,1]
train_perf = sc.perf_eva(y_train, train_pred, title = "train")
```

 **use score**: KS = 0.3449
```
train_pred_c= lr.predict(x_train)
sc.perf_eva(y_train,train_pred_c,title='ttt')
```
<img width="182" alt="1" src="https://user-images.githubusercontent.com/65208806/94509664-54964580-0247-11eb-8173-59bb5c2498d4.png">
<img width="167" alt="2" src="https://user-images.githubusercontent.com/65208806/94509665-552edc00-0247-11eb-86a1-c927f2b8a8ea.png">

hope for you help. thanks a lot.

**Comment by binxixi** [comment]
Besides, can I use stepwise to filter variables by scorecardpy?

**Comment by ShichenXie** [comment]
# Traditional Credit Scoring Using Logistic Regression
import scorecardpy as sc

# data prepare ------
# load germancredit data
dat = sc.germancredit()
# filter variable via missing rate, iv, identical value rate
dt_s = sc.var_filter(dat, y="creditability")
# breaking dt into train and test
train, test = sc.split_df(dt_s, 'creditability').values()

# woe binning ------
bins = sc.woebin(dt_s, y="creditability")

# converting train and test into woe values
train_woe = sc.woebin_ply(train, bins)
y_train = train_woe.loc[:,'creditability']
X_train = train_woe.loc[:,train_woe.columns != 'creditability']

# logistic regression ------
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(penalty='l1', C=0.9, solver='saga', n_jobs=-1)
lr.fit(X_train, y_train)
# lr.coef_
# lr.intercept_

# predicted proability
train_pred = lr.predict_proba(X_train)[:,1]

# performance ks & roc ------
sc.perf_eva(y_train, train_pred, title = "proba")
sc.perf_eva(y_train, train_score.score, title = "score")

**Comment by ShichenXie** [comment]
> Besides, can I use stepwise to filter variables by scorecardpy?

This feature is not included in this package yet.

**Comment by binxixi** [comment]
谢老师好，示例代码运行后，发现评估指标KS存在小的差异。不清楚差异的原因。（分别用train_pred /&nbsp;train_score.score做参数）
代码结果如下：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShichenXie/scorecardpy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月11日(星期天) 下午5:51
收件人:&nbsp;"ShichenXie/scorecardpy"<scorecardpy@noreply.github.com&gt;;
抄送:&nbsp;"李彬"<59015692@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ShichenXie/scorecardpy] perf_eva caculate (#63)





 
Traditional Credit Scoring Using Logistic Regression
 
import scorecardpy as sc
 
data prepare ------
 
load germancredit data
 
dat = sc.germancredit()
 
filter variable via missing rate, iv, identical value rate
 
dt_s = sc.var_filter(dat, y="creditability")
 
breaking dt into train and test
 
train, test = sc.split_df(dt_s, 'creditability').values()
 
woe binning ------
 
bins = sc.woebin(dt_s, y="creditability")
 
converting train and test into woe values
 
train_woe = sc.woebin_ply(train, bins)
 y_train = train_woe.loc[:,'creditability']
 X_train = train_woe.loc[:,train_woe.columns != 'creditability']
 
logistic regression ------
 
from sklearn.linear_model import LogisticRegression
 lr = LogisticRegression(penalty='l1', C=0.9, solver='saga', n_jobs=-1)
 lr.fit(X_train, y_train)
 
lr.coef_
 
lr.intercept_
 
predicted proability
 
train_pred = lr.predict_proba(X_train)[:,1]
 
performance ks &amp; roc ------
 
sc.perf_eva(y_train, train_pred, title = "proba")
 sc.perf_eva(y_train, train_score.score, title = "score")

**Comment by ShichenXie** [comment]
概率转评分会四舍五入，导致一些细小的差别

**Comment by binxixi** [comment]
明白了，感谢老师！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShichenXie/scorecardpy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 晚上9:53
收件人:&nbsp;"ShichenXie/scorecardpy"<scorecardpy@noreply.github.com&gt;;
抄送:&nbsp;"李彬"<59015692@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ShichenXie/scorecardpy] perf_eva caculate (#63)





 
概率转评分会四舍五入，导致一些细小的差别
