### ISSUE TITLE
Scorecardpy vs MinMaxScalar on numeric variables

### ISSUE THREAD

**Issue by hanzigs** [ShichenXie/scorecardpy#64]
Hi,
I am using scorecardpy for long time now, now I did a comparison of model metrics between two types of normalization

Norm1: Normalising all Features using scorecardpy
Vs
Norm2: Normalising Categorical Features using scorecardpy and Normalising Numeric Features with MinMaxScalar

I find the 2nd performance is better
Used same data, built Keras, RandomForest and XGBClassifier

![image](https://user-images.githubusercontent.com/30790120/95709930-6f3ad680-0cab-11eb-9e98-5fccdfff81d5.png)

![image](https://user-images.githubusercontent.com/30790120/95710197-ecfee200-0cab-11eb-8d68-f63e6f13afc7.png)

whether binning numeric variables is not that effective?

**Comment by ShichenXie** [comment]
The binning process is not required in tree models, such as rf, xgb.
