### ISSUE TITLE
setting the decimal placement from 0 to 2~3

### ISSUE THREAD

**Issue by sasistician** [ShichenXie/scorecardpy#65]
In the R version we can set the decimal placement value from 0 as being the default. Is there a way we can increase the decimal placement value in python version too.  This is required for sc.scorecard function.

**Comment by ShichenXie** [comment]
This feature has been added to the sc.scorecard function. Please update the latest version from github via `pip install git+git://github.com/shichenxie/scorecardpy.git`.
