### ISSUE TITLE
Calibrated model in scorecard

### ISSUE THREAD

**Issue by Alinemm** [ShichenXie/scorecardpy#67]
Hi,

first of all, your solution is so useful. Thank you for that!

I had problems to put a calibrated model (using CalibratedClassifierCV) in scorecard function.

card = sc.scorecard(bins_adj, lr, X_train.columns , points0=p, pdo=pd)

Error message:
           "AttributeError: 'CalibratedClassifierCV' object has no attribute 'coef_'"

I would like to know if have you any mechanism to deal with that ? 
If not, I can do my mechanism and share to the community.

The best wishes.

**Comment by ShichenXie** [comment]
I dont know how to deal with the CalibratedClassifierCV objects in the scorecard function.  You can contribute to this project on this issue. Thanks.

**Comment by ShichenXie** [comment]
A new function `scorecard2` is added into this package, which requires binning from `woebin` function and  feature selected from the algorithms you choose.
