### ISSUE TITLE
关于变量筛选阈值设定的问题

### ISSUE THREAD

**Issue by chaoyue729** [ShichenXie/scorecardpy#7]
我在调用您的工具包时发现有数据空值率92%，但是iv在初筛的时候还可以满足0.02的标准，但是在woe分箱后iv就不满足了，手动分箱时会出现错误'str' object cannot be interpreted as an integer这类错误，是不是应该在woe之后再测一次分箱iv筛选呢？

**Comment by ShichenXie** [comment]
分箱之前的iv和分箱之后的iv值是不一样的。分箱之前是将每个值当作一箱，分箱之后是将每个woe值当一箱。箱数越少iv值越低，也就是说分箱之后的iv通常都会小于分箱之前的。

手动分箱出现的错误最好能给个可重现例子。

**Comment by chaoyue729** [comment]
您需要的话，可以给您一份评分卡的数据；在手动分箱时会出现我说的那个类型的错误；我自己用字典解析，又筛选了一次 bins_adj = {k: v for k, v in bins.items() if bins[k].total_iv[0]>0.02}

**Comment by ShichenXie** [comment]
我一般是转woe值之后再用var_filter筛选一遍。

手动分箱是因为存在iv小于0.02的变量么？

**Comment by ShichenXie** [comment]
如果能用R，可以试试R版本的，会稳定很多而且速度更快。
