### ISSUE TITLE
pandas1.3/1.1   reset_index 没有 name 参数

### ISSUE THREAD

**Issue by fourjava** [ShichenXie/scorecardpy#76]
![1629084652(1)](https://user-images.githubusercontent.com/22856420/129507983-5753c16f-e3da-4645-8c72-5d7378ea0cf3.png)

woebin.py
  File "D:\Users\anaconda3\envs\py36\lib\site-packages\scorecardpy\woebin.py", line 579, in add_chisq
    chisq_df.groupby('brkp').apply(lambda df: sum(df.a+df.a_lag)).reset_index(name='a_sum'))\

**Comment by chenbofeng123** [comment]
请问这个解决了吗！！！！

**Comment by ShichenXie** [comment]
安装github上面的版本试试
