### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by Mennyyyyyys** [ShichenXie/scorecardpy#78]
环境：
python:3.8.5
pandas:1.3.2
numpy:1.21.2

问题1：
代码如下：
import pandas as pd
import numpy as np
a = pd.DataFrame({"a":[1,2,3,4,5,6]})
a.reset_index().rename({'index':'a'})
import scorecardpy as sc
a = pd.DataFrame({"a":[1,2,3,np.nan,5,6,7,4,4,5,3,4,1,6,53,54],"b":[1,0,0,0,1,1,1,0,0,0,1,1,1,1,1,1]})
bins = sc.woebin(a,y='b')
报错结果：Can only pass argument "on" OR "left_index" and "right_index", not a combination of both

**Comment by ShichenXie** [comment]
用的github上面的版本不能复现这个问题

**Comment by ShichenXie** [comment]
安装github上面的版本试试
