### ISSUE TITLE
Error when running # converting train and test into woe values

### ISSUE THREAD

**Issue by reza0184** [ShichenXie/scorecardpy#8]
When I'm running your example code using the same dataset, I got some error on this line :

#### #converting train and test into woe values
train_woe = sc.woebin_ply(train, bins_adj)
test_woe = sc.woebin_ply(test, bins_adj)

**ValueError: fill value must be in categories**

I would ask is there any step that I missed?

**Comment by reza0184** [comment]
Thanks, I already solve the problems

**Comment by ShichenXie** [comment]
good

**Comment by 77QingLiu** [comment]
@reza0184 How did you fix that?
