### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by xiaofengfengye** [ShichenXie/scorecardpy#90]
import scorecardpy as sc
dat = sc.germancredit()

bins = sc.woebin(dt_s, y="creditability")  运行这一步的时候报错，错误提示为：
TypeError: unhashable type: 'numpy.ndarray'

是不是源码有异常？
使用的版本是今天安装的最新版

**Comment by LunarAurora666** [comment]
the same error.

**Comment by ShichenXie** [comment]
你的dt_s哪来的，是不是写错了

**Comment by LunarAurora666** [comment]
> 你的dt_s哪来的，是不是写错了

就用了Example里的～

**Comment by ShichenXie** [comment]
改成dat吧，例子里的应该错了。
