### ISSUE TITLE
两个地方算出来的iv不同

### ISSUE THREAD

**Issue by RAO-sy** [ShichenXie/scorecardpy#93]
谢老师，您好！我在使用评分卡模型包的时候，发现var_filter中计算出来的iv值和使用woebin中计算出来的iv是不一样，前一个是没有分箱直接计算出来的iv，后一个是通过分箱计算出来的iv。那么问题来了，为什么变量筛选这一步不放在分箱后进行，而是一开始就进行变量筛选？

**Comment by ShichenXie** [comment]
通常分箱之后特征包含的信息会减少，对应的iv可能会降低、单一值率会增加。如果分箱之前这些指标很差，就没必要进一步分箱了。
