### ISSUE TITLE
Default values for pdo, points0 and odds0

### ISSUE THREAD

**Issue by hanzigs** [ShichenXie/scorecardpy#96]
Hi,

The default values in the scorecard function are given as 
```
    points0: Target points, default 600.
    odds0: Target odds, default 1/19. Odds = p/(1-p).
    pdo: Points to Double the Odds, default 50.
```

May I please know the reference for the default scores, just to understand the parameters in detail,
In general, people use PDO as 20 and Odds as 50:1, is there a specific reason the odds given as 19:1 and pdo as 50?
![image](https://user-images.githubusercontent.com/30790120/204457267-eda57e15-6050-431b-bf80-d8144ade2512.png)

Thanks in advance

**Comment by Blanket58** [comment]
The purpose to set odds to be 1/19 is to ensure we have the prior knowledge that when the score reaches 600 the bad rate is 5%.

```math
odds = \frac{p}{1-p} = \frac{1}{19}
```

```math
p = 0.05
```

The value of `points0` and `pdo` don't really matter, you can give the number whatever you want. And if you can read chinese, hope the blog below can help you.

https://blanket58.github.io/2021/12/scorecard/

**Comment by hanzigs** [comment]
Thank you very much for the explanation, much appreciated, Blog helped as well.
