### ISSUE TITLE
改造评分卡的预测模型

### ISSUE THREAD

**Issue by autogluonisgod** [ShichenXie/scorecardpy#99]
我想用autogluon改造一下这个评分卡去使用，但是出现一个错误，代码是这样
`card = sc.scorecard(bins, predictor, X_train.columns)`
我用predictor我预测模型替换了默认的lr模型，结果就报错了
'TabularPredictor' object has no attribute 'coef_'
怎么改动可以解决这个问题啊

**Comment by XingkunAn** [comment]
similar problem，也想请教一下作者是否有办法
card = sc.scorecard(bins_adj,lr,model_collist,points0=600, odds0=1/20, pdo=20, basepoints_eq0=False)
所有的参数都是正常的，会报错
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-129-6df8d4e8bdf2> in <module>
----> 1 card = sc.scorecard(bins_adj,lr,model_collist,points0=600, odds0=1/20, pdo=20, basepoints_eq0=False)

~/opt/anaconda3/lib/python3.7/site-packages/scorecardpy/scorecard.py in scorecard(bins, model, xcolumns, points0, odds0, pdo, basepoints_eq0)
    112     xs = [re.sub('_woe$', '', i) for i in xcolumns]
    113     # coefficients
--> 114     coef_df = pd.Series(model.coef_[0], index=np.array(xs))\
    115       .loc[lambda x: x != 0]#.reset_index(drop=True)
    116 

~/opt/anaconda3/lib/python3.7/site-packages/statsmodels/base/wrapper.py in __getattribute__(self, attr)
     33             pass
     34 
---> 35         obj = getattr(results, attr)
     36         data = results.model.data
     37         how = self._wrap_attrs.get(attr)

AttributeError: 'LogitResults' object has no attribute 'coef_'
